slack:
  report_channel: SLACK_REPORT_CHANNEL
  report_channel_id: SLACK_REPORT_CHANNEL_ID

jira:
  start_transition_id: JIRA_START_TRANSITION_ID
  done_transition_id: JIRA_DONE_TRANSITION_ID
  project: JIRA_PROJECT

secrets:
  cftptl-intsvc:
    jira-username: JIRA_USERNAME
    jira-api-token: JIRA_API_TOKEN
    idam-slack-bot-token: SLACK_BOT_TOKEN
    idam-slack-app-token: SLACK_APP_TOKEN
