slack:
  report_channel: SLACK_REPORT_CHANNEL
  report_channel_id: SLACK_REPORT_CHANNEL_ID

jira:
  project: JIRA_PROJECT

secrets:
  cftptl-intsvc:
    jira-username: JIRA_USERNAME
    jira-api-token: JIRA_API_TOKEN
    idam-slack-bot-token: SLACK_BOT_TOKEN
    idam-slack-app-token: SLACK_APP_TOKEN

service-refresh-time: 15