# defaults are setup for the platform engineering slack workspace
slack:
  #bot_token: no default
  #app_token: no default
  report_channel: bot-test
  report_channel_id: C01KHKNJUKE

jira:
  #username: no default
  #api_token: no default
  start_transition_id: 21
  done_transition_id: 41
  project: SBOX
  issue_type_id: Bug
  issue_type_name: 10900

secrets:
  cftptl-intsvc:
    jira-username: JIRA_USERNAME
    jira-api-token: JIRA_API_TOKEN
    slack-bot-token: SLACK_BOT_TOKEN
    slack-app-token: SLACK_APP_TOKEN
